### ISSUE TITLE
Need to re-start atom before ghc-mod works with stack

### ISSUE THREAD

**Issue by BillyBadBoy** [atom-haskell/haskell-ghc-mod#165]
steps to reproduce:

- reboot machine
- open stack project using atom 
- result: ghc-mod fails because `stack path` fails

However, if I close and re-open atom (sometimes several times) it works OK.

----

I've noticed that if I re-boot my machine and run 
`stack path --snapshot-install-root --local-install-root` from the command line it takes a long time to run the first time (over 5 seconds), but runs quickly when re-run. (If I then run atom it works first time.)

----

Is there some kind of timeout issue tricking atom into thinking that `stack path` has failed ?

**Comment by lierdakil** [comment]
There is indeed a timeout for some initialization operations, misnamed `syncTimeout`. You can change that in settings. Note that I pushed out 1.15.2 which has that renamed to `initTimeout` with a more accurate description and also raised it from 5 to 60 seconds (there's no need for a short timeout now, since it doesn't block Atom anymore, but a reasonable timeout is still a good idea generally to avoid infinite wait times). You might want to update.

**Comment by BillyBadBoy** [comment]
updated... and now it works !!!
