### ISSUE TITLE
Object.observe is not a function

### ISSUE THREAD

**Issue by remexre** [atom-haskell/haskell-ghc-mod#168]
Occurs on start, always. It seems to be true on Atom 1.9.8; Object.observe is undefined in the Developer Console too.

**Comment by lierdakil** [comment]
Should be fixed in 1.16.1, although this introduces a small resource leak on linter package deactivation, if you have 'Use Linter' option enabled. Everything should be fine unless you keep de- and re-activating linter package for a million times.... I will rewrite linter integration one of these days. At least that's what I keep telling myself.

**Comment by remexre** [comment]
Yep, fixed. Thanks!
