### ISSUE TITLE
ghc-mod -> check does not working (on check, on save)

### ISSUE THREAD

**Issue by dontdieych** [atom-haskell/haskell-ghc-mod#190]
I've got working project. Working means do check well on save and on change.

I've cloned that repo and create another repo. Say a, b and c procject. a is working good. b is cloned from a. c is new one.

Why haskell-ghc-mod does not working on b and c?

I opened c folder then 'ctrl-shift+p' then type 'ghc mod' and it only shows 'Haskell Ghc Mod: Shutdown Backend' item. When I tried same thing in a folder, it shows bunch of ghc-mod command items.

Any advice would be appreciated.

Thanks.

**Comment by lierdakil** [comment]
I'm sorry, but english is not my native language, and apparently neither is it yours. So I'm having a *really* hard time understanding what the problem is exactly.

Could you maybe try to explain in more detail? Possibly attach a couple screenshots to illustrate the problem?

Thanks.

**Comment by dontdieych** [comment]
haskell project a :
    created by 'stack new .....' command
    working good on save and on change
    can find bunch of ghc-mod commands in atom command
launcher(ctrl-shift-p)

project b :
    created by git clone froma project a
    manual ghc-mod check does not working. on save and on change ghc-mod
check does not working
    cannot find ghc-mod commands on atom command launcher except shutdown
backend

project c :
    created by 'stack new ...' command
    same problem like project b




2016. 11. 20. 오후 8:57에 "Nikolay Yakimov" <notifications@github.com>님이 작성:

I'm sorry, but english is not my native language, and apparently neither is
it yours. So I'm having a *really* hard time understanding what the problem
is exactly.

Could you maybe try to explain in more detail? Possibly attach a couple
screenshots to illustrate the problem?

Thanks.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/atom-haskell/haskell-ghc-mod/issues/190#issuecomment-261773865>,
or mute the thread

**Comment by lierdakil** [comment]
> cannot find ghc-mod commands on atom command launcher except shutdown
backend

This would indicate that ide-haskell didn't start for some reason. h-g-m heavily depends on ide-haskell for doing gui stuff.

Make sure ide-haskell is a) installed b) enabled

If everything seems to be in order, make sure 'Use Linter' h-g-m option is disabled, unless you have `linter` package installed and want to use it instead of ide-haskell for error/warning/whatever reports.

If nothing helps, post output of `atom --version` here. It's entirely possible that something's just broken in newer Atom version (or it's not outside the realm of possibility that you're using older Atom version). That said, if this was introduced by new Atom version, I'd expect there were more bug reports.
