### ISSUE TITLE
Incorrect advice when cabal-helper-wrapper not found

### ISSUE THREAD

**Issue by retep007** [atom-haskell/haskell-ghc-mod#214]
Error message advises to use
`export cabal_helper_libexecdir=$PWD/dist/build/cabal-helper-wrapper` which is not correct.
In fact, it requires to use
`export cabal_helper_libexecdir=$PWD/dist/build/`
It's really hard to tell what's happening when someone uses advised export.

**Comment by DanielG** [comment]
You are not really intended to do this if you're merely using cabal-helper (via ghc-mod), only if you're using an in-place compiled version because you are actively working on cabal-helper itself. If you just installed cabal-helper via cabal (or as a dependency of another package) this should really not happen. Most likely something went wrong during installation or you have deleted the cabal-helper-wrapper executable.
