### ISSUE TITLE
A way to display errors in different non-intrusive way

### ISSUE THREAD

**Issue by varosi** [atom-haskell/haskell-ghc-mod#215]
Pop-up errors often are very annoying. Currenly most often when I switch between projects with different LTS (GHC) versions - ghd-mod is complaining. And even if I would like just to browse/view the project - I get pop-up errors into my face.

May be those should be warnings, because nothing fatal is happened.

**Comment by DanielG** [comment]
Could you show us some of the error you're getting so we can discuss their severity?

**Comment by varosi** [comment]
![untitled](https://user-images.githubusercontent.com/6051718/26972529-eb9372ea-4d1a-11e7-9839-4fff3158c24a.png)

Even if I just want to browse some older project I get this annoying errors. I know that I could not get type information because of this errors, but it should be a warning, not an error. It's better to browse my project peacefully than to fight with those messages. The problem is even worse on smaller resolution displays.

**Comment by lierdakil** [comment]
You can suppress error popups. See
https://atom-haskell.github.io/core-packages/haskell-ghc-mod/#advanced-configuration.
Errors are duplicated to dev. console either way, so you can still
troubleshoot if you need to. FYI, Atom handles warnings as pop-ups as well,
so that woudn't solve the problem.

Error handling was done this way primarily to encourage feedback,
especially since ghc-mod's error messages can be rather cryptic to new
users. Maybe it's about time I reevaluated this strategy.

пт, 9 июн. 2017 г. в 13:55, varosi <notifications@github.com>:

**Comment by varosi** [comment]
Thank you very much, again! Advanced configuration solved my problem!
