### ISSUE TITLE
Failed to spawn command `ghc-mod`

### ISSUE THREAD

**Issue by mpickering** [atom-haskell/haskell-ghc-mod#38]
`ghc-mod` is on my path.

```
> ghc-mod --version
ghc-mod version 0 compiled by GHC 7.10.1
```

Any ideas?

**Comment by lierdakil** [comment]
Hi there.

If you're on OS X, then bear in mind that when you launch Atom from Finder, it doesn't pick up on shell environment (including user-configured PATH). Try starting Atom from terminal. You can specify PATH in haskell-ghc-mod settings, if it's the case.

Otherwise (or if it doesn't help), please enable 'Debug' option in haskell-ghc-mod settings, and post dev. console output here (View -> Developer -> Toggle Developer Tools). Hopefully, it will provide enough information to go on.

**Comment by lierdakil** [comment]
Also, see #18.

**Comment by mpickering** [comment]
Thank works thanks. Is this expected behaviour or a bug in atom?

**Comment by lierdakil** [comment]
You might consider it both. Technically, as far as I understand, Finder doesn't use interactive shell, so it doesn't pick up environment from `.*sh_profile`/`.*shrc`, and uses its own environment instead, so it's expected behavior. That said, it's very counter-intuitive, so it can be considered a bug. It's been reported, but no milestone yet: https://github.com/atom/atom/issues/6956
